name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install --only dev
      - run: black --line-length=120 --check .
      - run: isort --check --line-length 120 --profile black .
      - run: ruff check .
  build:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: build
    runs-on: ubuntu-latest
    needs: [ tests ]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - run: echo "container_tag=$(date +'%FT%H%M%SZ')" >> $GITHUB_ENV
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/binkhq/${{ github.event.repository.name }}:${{ env.container_tag }}
          ghcr.io/binkhq/${{ github.event.repository.name }}:latest